package SimpleGUI;

import SimpleCharacters.Archer;
import SimpleCharacters.Hero;
import SimpleCharacters.Swordsman;
import SimpleCharacters.Wizard;
import javax.swing.JFrame;

//second frame

public class ChooseHero extends javax.swing.JFrame{

    public static Hero Hero;
    public static String HeroText;
    
    private static JFrame frame = new JFrame();

    /**
     * Creates new form ChooseHeroGUI
     */
    public ChooseHero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CharactersComboBox = new javax.swing.JComboBox<>();
        TitleLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HeroNationalityText = new javax.swing.JTextField();
        HeroNameText = new javax.swing.JTextField();
        ConfirmHeroButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        HeroTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        EndButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RestartButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        HeroStatsArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adopt a Pet");
        setMinimumSize(new java.awt.Dimension(600, 570));
        getContentPane().setLayout(null);

        CharactersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"--Select Option--", "Dog", "Cat", "Rabbit" }));
        CharactersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharactersComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CharactersComboBox);
        CharactersComboBox.setBounds(176, 62, 120, 23);

        TitleLabel1.setBackground(new java.awt.Color(255, 255, 0));
        TitleLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TitleLabel1.setText("Choose Your Hero");
        TitleLabel1.setOpaque(true);
        getContentPane().add(TitleLabel1);
        TitleLabel1.setBounds(50, 20, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nationality:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 90, 30);

        HeroNationalityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroNationalityTextActionPerformed(evt);
            }
        });
        getContentPane().add(HeroNationalityText);
        HeroNationalityText.setBounds(140, 140, 110, 30);

        HeroNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeroNameTextActionPerformed(evt);
            }
        });
        getContentPane().add(HeroNameText);
        HeroNameText.setBounds(140, 100, 110, 30);

        ConfirmHeroButton.setBackground(new java.awt.Color(255, 255, 51));
        ConfirmHeroButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConfirmHeroButton.setText("Comfirm");
        ConfirmHeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmHeroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmHeroButton);
        ConfirmHeroButton.setBounds(420, 90, 110, 40);

        HeroTextArea.setColumns(20);
        HeroTextArea.setRows(5);
        jScrollPane2.setViewportView(HeroTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 180, 244, 212);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(271, 198, 0, 0);

        EndButton.setBackground(new java.awt.Color(255, 255, 0));
        EndButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EndButton.setText("End");
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EndButton);
        EndButton.setBounds(490, 20, 70, 30);

        questionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        questionLabel.setText("Hero's Occupation");
        getContentPane().add(questionLabel);
        questionLabel.setBounds(40, 60, 125, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Hero Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 100, 17);

        RestartButton.setBackground(new java.awt.Color(255, 255, 0));
        RestartButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RestartButton.setText("Restart");
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RestartButton);
        RestartButton.setBounds(400, 20, 80, 30);

        jPanel1.setLayout(null);

        HeroStatsArea.setColumns(20);
        HeroStatsArea.setRows(5);
        jScrollPane4.setViewportView(HeroStatsArea);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(310, 180, 250, 212);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HeroSelectBG.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-620, -280, 1420, 820);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 650, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Retrieves animal info depending on user selection
    private void CharactersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharactersComboBoxActionPerformed

        if("Swordsman".equals(CharactersComboBox.getSelectedItem().toString())){
            HeroTextArea.setText("");
            String nameSwordsman = HeroNameText.getText().trim();
            String nationalitySwordsman = HeroNationalityText.getText().trim();

            ChooseHero.Hero = new Swordsman(nameSwordsman, nationalitySwordsman);
            HeroStatsArea.setText("\n" + Hero.printInfo());
            ChooseHero.HeroText = this.HeroTextArea.getText();
        }
        if("Wizard".equals(CharactersComboBox.getSelectedItem().toString())){
            HeroTextArea.setText("");
            String nameWizard = HeroNameText.getText().trim();
            String nationalityWizard = HeroNationalityText.getText().trim();

            ChooseHero.Hero = new Wizard(nameWizard, nationalityWizard);
            HeroStatsArea.setText("\n" + Hero.printInfo());
            ChooseHero.HeroText = this.HeroTextArea.getText();
        }
        if("Archer".equals(CharactersComboBox.getSelectedItem().toString())){
            HeroTextArea.setText("");
            String nameArcher = HeroNameText.getText().trim();
            String nationalityArcher = HeroNationalityText.getText().trim();

            ChooseHero.Hero = new Archer(nameArcher, nationalityArcher);
            HeroStatsArea.setText("\n" + Hero.printInfo());
            ChooseHero.HeroText = this.HeroTextArea.getText();
        }

    }//GEN-LAST:event_CharactersComboBoxActionPerformed

    private void HeroNationalityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroNationalityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeroNationalityTextActionPerformed

    private void HeroNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeroNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeroNameTextActionPerformed
    //Display message pushing user to select option before continuing
    private void ConfirmHeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmHeroButtonActionPerformed
        // TODO add your handling code here:
        if ("Select Occupation".equals(CharactersComboBox.getSelectedItem().toString())){
            String text = "Please select a Hero!";
            HeroStatsArea.setText(text);
        }else if ("".equals(HeroNameText.getText())){
            String text = "Please enter a name!";
            HeroStatsArea.setText(text);      
        }else if ("".equals(HeroNationalityText.getText())){
            String text = "Please enter a nationality!";
            HeroStatsArea.setText(text);      
        }else if ("".equals(HeroNameText.getText()) && "".equals(HeroNationalityText.getText())){
            String text = "Please enter a name and nationality!";
            HeroStatsArea.setText(text);      
        }else {
            Hero.setanimalName(HeroNameText.getText());
            Hero.setColour(HeroNationalityText.getText());
            HeroTextArea.append("\nYour Hero details:");
            HeroTextArea.append("\nName: " + Hero.getanimalName());
            HeroTextArea.append("\nNationality: " + Hero.getColour());
            ChooseHero.HeroText = this.HeroTextArea.getText();
            new HeroActions().setVisible(true);
            ChooseHero.super.dispose();
        }
        
    }//GEN-LAST:event_ConfirmHeroButtonActionPerformed

    //end program
    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EndButtonActionPerformed

    //restart program
    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
         new IntroductionFrame().setVisible(true);
    }//GEN-LAST:event_RestartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new ChooseHero();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CharactersComboBox;
    private javax.swing.JButton ConfirmHeroButton;
    private javax.swing.JButton EndButton;
    public javax.swing.JTextField HeroNameText;
    public javax.swing.JTextField HeroNationalityText;
    private javax.swing.JTextArea HeroStatsArea;
    private javax.swing.JTextArea HeroTextArea;
    private javax.swing.JButton RestartButton;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables

}
