package SimpleGUI;

import javax.swing.JFrame;

//starting frame
public class IntroductionFrame extends JFrame {
    
   private static JFrame frame = new JFrame();
   public static PlayerReport player;

    /**
     * Creates new form IntroductionFrame
     */
    public IntroductionFrame() {
        player = new PlayerReport();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameField = new javax.swing.JTextField();
        ContinueButton = new javax.swing.JButton();
        HowToPlayButton = new javax.swing.JButton();
        EndButton = new javax.swing.JButton();
        TitleLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Introduction ");
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameField);
        NameField.setBounds(310, 240, 140, 30);

        ContinueButton.setBackground(new java.awt.Color(255, 255, 0));
        ContinueButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ContinueButton);
        ContinueButton.setBounds(220, 310, 120, 40);

        HowToPlayButton.setBackground(new java.awt.Color(255, 255, 0));
        HowToPlayButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HowToPlayButton.setText("How to Play");
        HowToPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToPlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HowToPlayButton);
        HowToPlayButton.setBounds(200, 140, 130, 50);

        EndButton.setBackground(new java.awt.Color(255, 255, 0));
        EndButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EndButton.setText("End");
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EndButton);
        EndButton.setBounds(40, 20, 72, 23);

        TitleLabel1.setBackground(new java.awt.Color(255, 255, 0));
        TitleLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        TitleLabel1.setText("Welcome to SimpleRPG");
        getContentPane().add(TitleLabel1);
        TitleLabel1.setBounds(140, 70, 260, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("  Please enter your name:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 240, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IntroBG.jpg")));
        jLabel1.setMaximumSize(new java.awt.Dimension(750, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jLabel1.setName("Virtual Hero Game Introduction"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -70, 590, 560);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 400);

        setSize(new java.awt.Dimension(550, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    //to continue a name must be entered
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        // TODO add your handling code here:
        if("".equals(NameField.getText())){
            String text = "Please enter player name to continue!";
            new GUI("Enter Name!", text);
       }else{
            player.setUsername(NameField.getText());
            IntroductionFrame.super.dispose();
            new ChooseHero().setVisible(true);
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    //shows the game manual
    private void HowToPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToPlayButtonActionPerformed
        // TODO add your handling code here:
        Manual.main();
    }//GEN-LAST:event_HowToPlayButtonActionPerformed

    //end program
    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EndButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        IntroductionFrame.jPanel1 = new Panel();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroductionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frame = new IntroductionFrame();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueButton;
    private javax.swing.JButton EndButton;
    private javax.swing.JButton HowToPlayButton;
    public javax.swing.JTextField NameField;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}

